# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6792dd1d8809da60e26f270fd75092054d80d290a2ae147757a3ff016073bcfa74b871cb113fd8c987e335d52b1b597b27221619e1cbb8e97247ed0df6bd5b1b

test:
  secret_key_base: b5dcc8aaff7a66d1c299c584326531d9f036779103d03ac70dc6408af5e42fb68750e34ea6ea9264ca4112f8a6a1c222b1b0e798267408a343d8c4e9979e9201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
